### ISSUE TITLE
Linux下模块编译问题

### ISSUE THREAD

**Issue by ycjcl868** [wssgcg1213/ling-cet-decoder#2]
本地用Mac开发，直接npm install，可以使用。部署到服务器时，报错

```
tdecoder-main.node: invalid ELF header
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/wwwroot/cet.ycjcl.cc/node_modules/ling-cet-decoder/index.js:5:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

```

google,stackoverflow后，发现需要安装一个[模块bcrypt](http://stackoverflow.com/questions/15809611/bcrypt-invalid-elf-header-when-running-node-app)。安装后，再npm install ，linux上正常。

**Comment by wssgcg1213** [comment]
c++模块应该是只依赖了openssl 
check一下openssl的依赖
一般来说装好build_essential就没有什么问题了

**Comment by wssgcg1213** [comment]
你的linux环境信息能提供一下么

**Comment by ycjcl868** [comment]
CentOS Linux release 7.0.1406，gcc 版本 4.8.3, node v4.4.3,
